# Generated by Django 2.2.1 on 2019-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='relationship',
        ),
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.ManyToManyField(related_name='_user_relationship_+', to='repository.User'),
        ),
    ]
