# Generated by Django 2.2.1 on 2019-09-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190919_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f', to='repository.User', verbose_name='关注者')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s', to='repository.User', verbose_name='被关注者')),
            ],
            options={
                'verbose_name_plural': '互粉表',
            },
        ),
    ]
