# Generated by Django 2.2.1 on 2019-09-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20190919_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('summary', models.TextField(verbose_name='文字简介')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='ArticleDetial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='文章正文')),
            ],
            options={
                'verbose_name_plural': '文章正文',
            },
        ),
        migrations.AlterModelOptions(
            name='reporting',
            options={'verbose_name_plural': '报障单'},
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_relationship_+', to='repository.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article', verbose_name='文章')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='博客分类')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Blog', verbose_name='博客')),
            ],
            options={
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='博客标签')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Blog', verbose_name='博客')),
            ],
            options={
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleDetial', verbose_name='文章正文'),
        ),
        migrations.CreateModel(
            name='ArticleToCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article', verbose_name='文章')),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Caption', verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '文章列表',
                'unique_together': {('article', 'caption')},
            },
        ),
    ]
