# Generated by Django 2.2.1 on 2019-09-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20190919_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletocaption',
            options={'verbose_name_plural': '文章标签关系'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.CreateModel(
            name='Perference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfer', models.NullBooleanField(verbose_name='偏好')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '踩赞表',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
