# Generated by Django 2.2.1 on 2019-09-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20190921_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relationship',
        ),
    ]
