# Generated by Django 2.2.1 on 2019-09-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_remove_user_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[(1, 'Python'), (2, 'Java'), (3, 'C++'), (4, 'JavaScript')], default=1, max_length=25, verbose_name='文章类型'),
        ),
    ]
