# Generated by Django 2.2.1 on 2019-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Java'), (3, 'C++'), (4, 'JavaScript')], verbose_name='文章类型'),
        ),
    ]
