# Generated by Django 2.2.1 on 2019-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20190923_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='1', max_length=25, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, verbose_name='用户昵称'),
        ),
    ]
