# Generated by Django 2.2.1 on 2019-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20190926_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=25, unique=True, verbose_name='用户名'),
        ),
    ]
