# Generated by Django 2.2.1 on 2019-09-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20190926_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(default='123', max_length=25, verbose_name='用户名'),
        ),
    ]
