# Generated by Django 2.2.1 on 2019-09-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20190926_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
    ]
