# Generated by Django 2.2.1 on 2019-09-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
    ]
