# Generated by Django 2.2.1 on 2019-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_remove_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='123', max_length=25, verbose_name='用户名'),
        ),
    ]
