# Generated by Django 2.2.1 on 2019-09-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20190926_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='surfix',
        ),
    ]
